spring:
  application:
    name: purchase-service
  config:
    import: optional:configserver:http://config-service:9001
config:
  debitcard:
    endpoint: http://debitcard-service/debitcard
  transaction:
    endpoint: http://transaction-service/transaction