spring:
  application:
    name: withdrawal-service
  config:
    import: optional:configserver:http://localhost:9001
config:
  debitcard:
    endpoint: http://debitcard-service/debitcard
  transaction:
    endpoint: http://transaction-service/transaction