spring:
  application:
    name: signatory-service
  config:
    import: optional:configserver:http://config-service:9001
config:
  product:
    endpoint: http://product-service/product
  customer:
    endpoint: http://customer-service/customer
  transaction:
    endpoint: http://transaction-service/transaction